name: Export Pluto notebooks
on:
    workflow_dispatch:

jobs:
    build-and-deploy:
        timeout-minutes: 30
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install Julia
              uses: julia-actions/setup-julia@v2
              with:
                  version: "1"

            - name: Run & export Pluto notebooks
              run: |
                julia -e 'using Pkg
                  Pkg.activate(mktempdir())
                  Pkg.add([
                    Pkg.PackageSpec(name="PlutoSliderServer", version="1"),
                  ])

                  import PlutoSliderServer

                  PlutoSliderServer.github_action(".";
                    Export_cache_dir="pluto_state_cache",
                    Export_baked_notebookfile=false,
                    Export_baked_state=false,
                    # more parameters can go here
                  )'

            - name: Deploy to gh-pages
              uses: JamesIves/github-pages-deploy-action@releases/v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  branch: gh-pages
                  folder: .
                  single-commit: true
